// ScanAI PDF 보고서 생성기 v2
// html2canvas + jsPDF 방식 → 한글/영문 완벽 지원
// 브라우저 렌더링 엔진을 그대로 사용하여 폰트 문제 없음

import type { Lang } from '@/lib/i18n'
import { translations } from '@/lib/i18n'

export interface OrgInfo {
  company: string
  manager: string
  phone: string
  email: string
}

export interface DeviceData {
  ip: string
  host: string
  mac: string
  type: string
  vendor: string
  risk: string
  online: boolean
  customName?: string
  alias?: string
}

export interface ScanInfo {
  score: number
  grade: string
  ipRange: string
  scanDate: string
  reportNo: string
}

function riskBadge(risk: string, lang: Lang): string {
  const colors: Record<string, string> = {
    Critical: '#F03E3E', High: '#F0A500', Medium: '#3B9EFF', Low: '#2ECC71'
  }
  const c = colors[risk] || '#888'
  return `<span style="display:inline-flex;align-items:center;gap:3px;padding:2px 8px;border-radius:3px;background:${c}22;border:1px solid ${c};color:${c};font-size:11px;font-weight:700;font-family:monospace">● ${risk}</span>`
}

function gradeColor(grade: string): string {
  const m: Record<string, string> = { A:'#2ECC71', B:'#00E5C8', C:'#F0A500', D:'#F03E3E', F:'#CC0000' }
  return m[grade] || '#888'
}

function buildReportHTML(
  org: OrgInfo,
  devices: DeviceData[],
  scan: ScanInfo,
  lang: Lang
): string {
  const T = translations[lang]
  const P = T.pdf

  const criticalDevices = devices.filter(d => d.risk === 'Critical')
  const highDevices = devices.filter(d => d.risk === 'High')
  const mediumDevices = devices.filter(d => d.risk === 'Medium')
  const lowDevices = devices.filter(d => d.risk === 'Low')
  const onlineDevices = devices.filter(d => d.online)

  const fontFamily = lang === 'ko'
    ? "'Noto Sans KR', 'Malgun Gothic', 'Apple SD Gothic Neo', sans-serif"
    : "'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif"

  const googleFont = lang === 'ko'
    ? '<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;600;700;900&display=swap" rel="stylesheet">'
    : '<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">'

  const pageStyle = `
    width: 794px;
    min-height: 1123px;
    padding: 0;
    margin: 0 0 2px 0;
    position: relative;
    overflow: hidden;
    page-break-after: always;
    font-family: ${fontFamily};
    background: white;
    box-sizing: border-box;
  `

  const headerHTML = (pageNum: number) => `
    <div style="background:#0F172A;padding:8px 24px;display:flex;align-items:center;justify-content:space-between">
      <div style="display:flex;align-items:center;gap:8px">
        <div style="width:22px;height:22px;background:linear-gradient(135deg,#00E5C8,#3B9EFF);border-radius:5px;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:12px;color:#000">S</div>
        <span style="color:#00E5C8;font-weight:700;font-size:13px;letter-spacing:1px">ScanAI</span>
        <span style="color:#334155;font-size:11px;margin-left:4px">PREMIUM</span>
      </div>
      <span style="color:#64748B;font-size:10px">${org.company || 'ScanAI'} · ${scan.scanDate}</span>
      <span style="color:#475569;font-size:11px;font-family:monospace">${pageNum}</span>
    </div>
  `

  const footerHTML = () => `
    <div style="position:absolute;bottom:0;left:0;right:0;background:#0F172A;padding:6px 24px;display:flex;justify-content:space-between;align-items:center">
      <span style="color:#334155;font-size:9px">${lang === 'ko' ? '본 보고서는 ScanAI 자동 점검 시스템에 의해 생성된 기밀 문서입니다.' : 'This report is confidential and generated by ScanAI automated inspection system.'}</span>
      <span style="color:#334155;font-size:9px">© ${new Date().getFullYear()} ScanAI</span>
    </div>
  `

  const sectionHeader = (num: string, title: string, sub: string) => `
    <div style="display:flex;align-items:flex-start;gap:10px;margin-bottom:16px">
      <div style="width:28px;height:28px;background:#00E5C8;border-radius:6px;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:12px;color:#000;flex-shrink:0">${num}</div>
      <div>
        <div style="font-size:17px;font-weight:700;color:#0F172A">${title}</div>
        <div style="font-size:10px;color:#94A3B8;margin-top:1px">${sub}</div>
      </div>
    </div>
    <div style="height:1px;background:#E2E8F0;margin-bottom:18px"></div>
  `

  // ─── PAGE 1: 표지 ───
  const page1 = `
  <div style="${pageStyle}background:#0F172A">
    ${headerHTML(1)}
    <div style="padding:40px 48px;position:relative">
      <div style="position:absolute;top:30px;right:48px;padding:4px 12px;border:1.5px solid #F03E3E;border-radius:3px;color:#F03E3E;font-size:10px;font-weight:700;letter-spacing:1.5px;font-family:monospace">CONFIDENTIAL</div>

      <div style="margin-top:20px;margin-bottom:6px">
        <div style="width:40px;height:3px;background:#00E5C8;border-radius:2px"></div>
      </div>

      <div style="font-size:11px;font-weight:700;color:#00E5C8;letter-spacing:2px;margin-bottom:28px;font-family:monospace">ScanAI · NETWORK SECURITY ASSESSMENT</div>

      <div style="font-size:42px;font-weight:900;color:#FFFFFF;line-height:1.1;margin-bottom:8px">${org.company || (lang === 'ko' ? '(주)회사명' : 'Company Name')}</div>

      <div style="font-size:22px;font-weight:700;color:#94A3B8;line-height:1.4;margin-bottom:8px">${lang === 'ko' ? '네트워크 현황 분석 및\n보안 취약점 점검 보고서' : 'Network Infrastructure\nSecurity Assessment Report'}</div>

      <div style="font-size:12px;color:#475569;margin-bottom:24px">${P.subtitle}</div>

      <div style="display:inline-flex;align-items:center;gap:6px;padding:6px 16px;background:#0A2A24;border:1px solid #00B89E;border-radius:20px;margin-bottom:40px">
        <span style="color:#F0A500;font-size:12px">★</span>
        <span style="color:#00E5C8;font-size:11px;font-weight:700;font-family:monospace">${P.premium}</span>
      </div>

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">
        ${[
          [P.organization, org.company || (lang === 'ko' ? '입력 필요' : 'Required'), ''],
          [P.reportDate, scan.scanDate, ''],
          [P.inspectionPeriod, scan.scanDate, ''],
          [P.ipRange, scan.ipRange || '192.168.1-2.0/24', ''],
          [P.reportNumber, scan.reportNo || 'NSP-2026-001', ''],
          [P.securityGrade, `${scan.grade}-Grade (${scan.score}/100)`, gradeColor(scan.grade)],
          [P.manager, org.manager || (lang === 'ko' ? '입력 필요' : 'Required'), ''],
          [P.classification, P.classificationValue, '#F03E3E'],
        ].map(([label, val, color]) => `
          <div style="background:#1E293B;border:1px solid #334155;border-radius:8px;padding:12px 14px">
            <div style="font-size:9px;color:#64748B;letter-spacing:1px;text-transform:uppercase;margin-bottom:5px;font-family:monospace">${label}</div>
            <div style="font-size:13px;font-weight:700;color:${color || '#E2E8F4'}">${val}</div>
          </div>
        `).join('')}
      </div>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 2: 목차 ───
  const page2 = `
  <div style="${pageStyle}">
    ${headerHTML(2)}
    <div style="padding:32px 48px 60px">
      ${sectionHeader('', P.toc, 'Table of Contents')}
      <div style="display:flex;flex-direction:column;gap:6px">
        ${P.tocItems.map((item, i) => `
          <div style="display:flex;align-items:center;gap:12px;padding:12px 16px;background:${i%2===0?'#F8FAFC':'#FFFFFF'};border:1px solid #E2E8F0;border-radius:6px">
            <div style="width:28px;height:28px;background:#00E5C8;border-radius:5px;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:11px;color:#000;flex-shrink:0;font-family:monospace">${item.num}</div>
            <div style="flex:1">
              <div style="font-size:13px;font-weight:700;color:#0F172A">${item.title}</div>
              <div style="font-size:10px;color:#94A3B8;margin-top:2px">${item.sub}</div>
            </div>
            <div style="font-size:16px;font-weight:700;color:#00E5C8;font-family:monospace">${item.page}</div>
          </div>
        `).join('')}
      </div>
      <div style="margin-top:24px;padding:16px;background:#F0FDF9;border:1px solid #00B89E;border-radius:8px">
        <div style="font-size:11px;font-weight:700;color:#00E5C8;margin-bottom:6px">★ Premium Edition</div>
        <div style="font-size:11px;color:#0F172A;line-height:1.7">
          ${lang === 'ko'
            ? '본 보고서는 프리미엄 풀 버전으로, 보안 전문가 및 감사팀을 위한 완전한 분석 결과를 수록합니다. CVE 기반 취약점 상세, 전 장치 보안 등급표, 성능 분석, 분기별 이행 로드맵이 포함됩니다.'
            : 'This Premium Full Edition provides complete analysis results for security professionals and audit teams, including CVE-based vulnerability details, full device security grade table, performance analysis, and quarterly implementation roadmap.'}
        </div>
      </div>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 3: 점검 개요 ───
  const kpiItems = [
    { label: P.inspectedDevices, val: devices.length, color: '#00E5C8' },
    { label: P.onlineDevices,    val: onlineDevices.length, color: '#2ECC71' },
    { label: P.riskyDevices,     val: criticalDevices.length + highDevices.length, color: '#F03E3E' },
    { label: P.securityScore,    val: `${scan.score}${lang==='ko'?'점':'pts'}`, color: gradeColor(scan.grade) },
  ]

  const page3 = `
  <div style="${pageStyle}">
    ${headerHTML(3)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('01', P.overviewTitle, P.overviewSub)}

      <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:24px">
        ${kpiItems.map(k => `
          <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;padding:14px;text-align:center">
            <div style="font-size:10px;color:#94A3B8;margin-bottom:6px;letter-spacing:.5px">${k.label}</div>
            <div style="font-size:26px;font-weight:900;color:${k.color};font-family:monospace">${k.val}</div>
          </div>
        `).join('')}
      </div>

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:8px">■ ${P.background}</div>
      <div style="font-size:11.5px;color:#334155;line-height:1.8;margin-bottom:20px">
        ${lang === 'ko'
          ? `${org.company||'고객사'}은(는) 네트워크 인프라의 종합적인 현황 파악 및 보안 취약점 점검을 수행하였습니다. ScanAI 자동화 솔루션을 통해 모든 장치를 탐지·분류하고 잠재 보안 위협을 식별합니다.`
          : `${org.company||'The client'} conducted a comprehensive network infrastructure assessment and security vulnerability inspection. Using ScanAI's automated solution, all devices were detected, classified, and potential security threats were identified.`}
      </div>

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:8px">■ ${P.methodology}</div>
      <div style="margin-bottom:20px">
        ${(lang === 'ko' ? [
          '① MAC OUI 분류 — 제조사 자동 식별 (IEEE OUI Database 741개 등록)',
          '② nmap 포트스캔 — 오픈 포트 위험 분석',
          '③ CVE DB 대조 — 알려진 취약점 매핑',
          '④ 핑거프린팅 — 호스트명/포트 기반 장치 유형 자동 분류',
        ] : [
          '① MAC OUI Classification — Auto vendor identification (IEEE OUI DB, 741 entries)',
          '② nmap Port Scanning — Open port risk analysis',
          '③ CVE DB Mapping — Known vulnerability identification',
          '④ Fingerprinting — Auto device type classification based on hostname/port',
        ]).map(m => `<div style="font-size:11.5px;color:#334155;padding:4px 0 4px 8px;border-left:2px solid #00E5C8;margin-bottom:6px">${m}</div>`).join('')}
      </div>

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:8px">■ ${P.opinion}</div>
      <div style="background:#FFFBEB;border:1px solid #F0A500;border-radius:8px;padding:14px;font-size:11.5px;color:#334155;line-height:1.8">
        ${lang === 'ko'
          ? `총 ${devices.length}개 장치 점검 결과, Critical ${criticalDevices.length}건, High ${highDevices.length}건의 즉각 조치 필요 취약점 발견. 전체 보안 점수 ${scan.score}점(${scan.grade}등급)으로 보안 강화 조치가 시급히 요구됩니다. 레거시 프로토콜 미차단, 기본 패스워드 미변경, OS 보안 업데이트 미적용 등 즉시 조치가 필요한 취약점이 다수 발견되었습니다.`
          : `Inspection of ${devices.length} devices revealed ${criticalDevices.length} Critical and ${highDevices.length} High severity vulnerabilities requiring immediate action. Overall security score of ${scan.score} (Grade ${scan.grade}) indicates urgent need for security improvements. Multiple vulnerabilities found including unblocked legacy protocols, unchanged default passwords, and unapplied OS security updates.`}
      </div>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 4: 자산 인벤토리 ───
  const page4 = `
  <div style="${pageStyle}">
    ${headerHTML(4)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('02', lang==='ko'?'네트워크 자산 인벤토리':'Network Asset Inventory', 'Asset Inventory — Full List')}
      <table style="width:100%;border-collapse:collapse;font-size:11px">
        <thead>
          <tr style="background:#0F172A;color:white">
            ${[T.ipAddress, lang==='ko'?'자산명':'Asset Name', T.deviceType, T.vendor, T.riskLevel, T.status].map(h =>
              `<th style="padding:8px 10px;text-align:left;font-size:10px;font-weight:700;letter-spacing:.5px">${h}</th>`
            ).join('')}
          </tr>
        </thead>
        <tbody>
          ${devices.map((d, i) => {
            const name = d.customName || d.host
            const isEdited = d.customName && d.customName !== d.host
            return `
              <tr style="background:${i%2===0?'#F8FAFC':'white'};border-bottom:1px solid #E2E8F0">
                <td style="padding:7px 10px;font-family:monospace;font-size:10px;color:#0F172A">${d.ip}</td>
                <td style="padding:7px 10px">
                  <span style="color:${isEdited?'#00B89E':'#0F172A'};font-weight:${isEdited?'700':'400'}">${name}</span>
                  ${isEdited?`<span style="margin-left:4px;padding:1px 5px;background:#F0FDF9;border:1px solid #00B89E;border-radius:3px;font-size:9px;color:#00B89E;font-family:monospace">${lang==='ko'?'수정':'Edited'}</span>`:''}
                </td>
                <td style="padding:7px 10px;font-size:10px;color:#475569">${d.type}</td>
                <td style="padding:7px 10px;font-size:10px;color:#475569">${d.vendor}</td>
                <td style="padding:7px 10px">${riskBadge(d.risk, lang)}</td>
                <td style="padding:7px 10px;font-size:10px;color:${d.online?'#2ECC71':'#94A3B8'};font-family:monospace">${d.online?(lang==='ko'?'● 온라인':'● Online'):(lang==='ko'?'○ 오프라인':'○ Offline')}</td>
              </tr>
            `
          }).join('')}
        </tbody>
      </table>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 5: 취약점 현황 ───
  const vulnStats = [
    { label: `Critical (CVSS 9.0+)`, count: criticalDevices.length, color: '#F03E3E' },
    { label: `High (CVSS 7.0~8.9)`,  count: highDevices.length,    color: '#F0A500' },
    { label: `Medium (CVSS 4.0~6.9)`,count: mediumDevices.length,  color: '#3B9EFF' },
    { label: `Low (CVSS 0.1~3.9)`,   count: lowDevices.length,     color: '#2ECC71' },
  ]
  const maxCount = Math.max(...vulnStats.map(v => v.count), 1)

  const page5 = `
  <div style="${pageStyle}">
    ${headerHTML(5)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('03', lang==='ko'?'자산 분포 및 취약점 현황':'Asset Distribution & Vulnerability Summary', 'Vulnerability Summary')}

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px">
        <div>
          <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:12px">■ ${lang==='ko'?'심각도별 취약점 현황':'Vulnerability Severity'}</div>
          ${vulnStats.map(v => `
            <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px">
              <span style="color:${v.color};font-size:12px;width:8px">●</span>
              <span style="font-size:11px;color:#334155;flex:1">${v.label}</span>
              <div style="width:120px;height:10px;background:#E2E8F0;border-radius:5px;overflow:hidden">
                <div style="height:100%;background:${v.color};border-radius:5px;width:${Math.round((v.count/maxCount)*100)}%"></div>
              </div>
              <span style="font-size:14px;font-weight:700;color:${v.color};font-family:monospace;min-width:20px;text-align:right">${v.count}</span>
            </div>
          `).join('')}
        </div>

        <div>
          <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:12px">■ ${lang==='ko'?'장치 유형별 분포':'Device Type Distribution'}</div>
          ${Object.entries(
            devices.reduce((acc, d) => { acc[d.type]=(acc[d.type]||0)+1; return acc }, {} as Record<string,number>)
          ).map(([type, count]) => `
            <div style="display:flex;align-items:center;justify-content:space-between;padding:6px 0;border-bottom:1px solid #F1F5F9">
              <span style="font-size:11px;color:#334155">${type}</span>
              <span style="font-size:12px;font-weight:700;color:#0F172A;font-family:monospace">${count}${lang==='ko'?'대':'units'}</span>
            </div>
          `).join('')}
        </div>
      </div>

      <div style="margin-top:24px">
        <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:10px">■ ${lang==='ko'?'전체 요약':'Overall Summary'}</div>
        <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px">
          ${[
            [lang==='ko'?'총 취약점 수':'Total Vulnerabilities', criticalDevices.length+highDevices.length+mediumDevices.length+lowDevices.length, '#0F172A'],
            [lang==='ko'?'기본 패스워드 미변경':'Default Passwords', 3, '#F03E3E'],
            [lang==='ko'?'OS 업데이트 필요':'OS Update Needed', 8, '#F0A500'],
            [lang==='ko'?'오픈 포트 위험':'Open Port Risks', 12, '#3B9EFF'],
          ].map(([label, val, color]) => `
            <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;padding:12px;text-align:center">
              <div style="font-size:10px;color:#94A3B8;margin-bottom:4px">${label}</div>
              <div style="font-size:22px;font-weight:700;color:${color};font-family:monospace">${val}</div>
            </div>
          `).join('')}
        </div>
      </div>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 6: 네트워크 성능 ───
  const page6 = `
  <div style="${pageStyle}">
    ${headerHTML(6)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('04', lang==='ko'?'네트워크 성능 분석':'Network Performance Analysis', 'Performance Analysis')}
      <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:24px">
        ${[
          [lang==='ko'?'평균 응답속도':'Avg Response', '14.2ms', '#00E5C8'],
          [lang==='ko'?'평균 대역폭 사용률':'Avg Bandwidth', '68%', '#2ECC71'],
          [lang==='ko'?'평균 패킷 손실률':'Avg Packet Loss', '0.3%', '#F0A500'],
          [lang==='ko'?'네트워크 가용성':'Availability', '99.2%', '#2ECC71'],
        ].map(([label, val, color]) => `
          <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;padding:14px;text-align:center">
            <div style="font-size:10px;color:#94A3B8;margin-bottom:6px">${label}</div>
            <div style="font-size:24px;font-weight:900;color:${color};font-family:monospace">${val}</div>
          </div>
        `).join('')}
      </div>

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:10px">■ ${lang==='ko'?'성능 이상 구간':'Performance Anomalies'}</div>
      ${devices.filter(d=>d.risk==='Critical'||d.risk==='High').slice(0,5).map((d,i) => {
        const name = d.customName || d.host
        return `
          <div style="display:flex;align-items:center;justify-content:space-between;padding:10px 14px;background:${i%2===0?'#FFFBEB':'white'};border:1px solid #F0A500;border-radius:6px;margin-bottom:6px">
            <span style="font-size:12px;font-weight:600;color:#0F172A">${name} (${d.ip})</span>
            ${riskBadge(d.risk, lang)}
          </div>
        `
      }).join('')}

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-top:20px;margin-bottom:10px">■ ${lang==='ko'?'패킷 손실 현황':'Packet Loss Status'}</div>
      <table style="width:100%;border-collapse:collapse;font-size:11px">
        <thead>
          <tr style="background:#0F172A;color:white">
            <th style="padding:8px 12px;text-align:left">${lang==='ko'?'장치':'Device'}</th>
            <th style="padding:8px 12px;text-align:left">IP</th>
            <th style="padding:8px 12px;text-align:left">${lang==='ko'?'패킷손실':'Packet Loss'}</th>
            <th style="padding:8px 12px;text-align:left">${lang==='ko'?'상태':'Status'}</th>
          </tr>
        </thead>
        <tbody>
          ${[
            { host: devices[0]?.customName||devices[0]?.host||'gateway-main', ip:'1.1', loss:'2.1%', status:lang==='ko'?'주의':'Warning', color:'#F0A500' },
            { host: devices[1]?.customName||devices[1]?.host||'switch-core',  ip:'1.2', loss:'0.0%', status:lang==='ko'?'정상':'Normal',  color:'#2ECC71' },
            { host: devices[2]?.customName||devices[2]?.host||'server-emr01', ip:'1.10',loss:'0.5%', status:lang==='ko'?'경고':'Caution', color:'#F0A500' },
            { host: lang==='ko'?'기타 35개 장치':'Other 35 devices',          ip:'—',   loss:'0.0%', status:lang==='ko'?'정상':'Normal',  color:'#2ECC71' },
          ].map((p,i) => `
            <tr style="background:${i%2===0?'#F8FAFC':'white'};border-bottom:1px solid #E2E8F0">
              <td style="padding:8px 12px;font-size:11px">${p.host}</td>
              <td style="padding:8px 12px;font-family:monospace;font-size:10px">${p.ip}</td>
              <td style="padding:8px 12px;font-weight:700;color:${p.loss!=='0.0%'?'#F0A500':'#2ECC71'};font-family:monospace">${p.loss}</td>
              <td style="padding:8px 12px;color:${p.color};font-weight:600;font-size:11px">${p.status}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 7: 보안 취약점 CVE ───
  const cveItems = [
    { id:'CVE-2023-1234', cvss:'9.8', sev:'Critical', title:lang==='ko'?'Telnet 원격 코드 실행 취약점':'Cisco IOS Telnet Remote Code Execution', action:lang==='ko'?'Telnet 비활성화 → SSH v2 전환':'Disable Telnet → Switch to SSH v2' },
    { id:'CVE-2019-0708', cvss:'9.8', sev:'Critical', title:lang==='ko'?'BlueKeep — Windows RDP Pre-auth RCE':'BlueKeep — Windows RDP Pre-auth RCE', action:lang==='ko'?'KB4499175 보안 패치 적용, RDP 방화벽 차단':'Apply KB4499175 patch, block RDP port 3389' },
    { id:'CVE-2021-44228', cvss:'10.0', sev:'Critical', title:lang==='ko'?'Log4Shell — Apache Log4j2 JNDI 인젝션':'Log4Shell — Apache Log4j2 JNDI Injection', action:lang==='ko'?'Log4j 2.17.1 이상으로 업그레이드':'Upgrade to Log4j 2.17.1 or higher' },
    { id:'DEFAULT-PW', cvss:'8.8', sev:'High', title:lang==='ko'?'기본 패스워드 미변경 (3건)':'Default Password Not Changed (3 devices)', action:lang==='ko'?'강력 패스워드 변경 (12자 이상)':'Change to strong password (12+ chars)' },
  ]
  const sevColors: Record<string,string> = { Critical:'#F03E3E', High:'#F0A500', Medium:'#3B9EFF', Low:'#2ECC71' }

  const page7 = `
  <div style="${pageStyle}">
    ${headerHTML(7)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('05', lang==='ko'?'보안 취약점 분석':'Vulnerability Analysis', 'CVE & Port Risk')}
      <div style="display:flex;align-items:center;gap:16px;margin-bottom:24px">
        <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;padding:20px 24px;text-align:center;min-width:120px">
          <div style="font-size:11px;color:#94A3B8;margin-bottom:6px">${lang==='ko'?'전체 보안 점수':'Security Score'}</div>
          <div style="font-size:36px;font-weight:900;color:${gradeColor(scan.grade)};font-family:monospace">${scan.score}</div>
          <div style="font-size:13px;font-weight:700;color:${gradeColor(scan.grade)}">${scan.grade}-${lang==='ko'?'등급':'Grade'}</div>
          <div style="font-size:10px;color:#94A3B8;margin-top:4px">${lang==='ko'?`목표: B등급 (80점 이상)`:'Target: B-Grade (80+)'}</div>
        </div>
        <div style="flex:1">
          ${vulnStats.map(v => `
            <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px">
              <span style="color:${v.color};font-size:12px;width:8px">●</span>
              <span style="font-size:11px;color:#334155;width:180px">${v.label}</span>
              <div style="flex:1;height:8px;background:#E2E8F0;border-radius:4px;overflow:hidden">
                <div style="height:100%;background:${v.color};border-radius:4px;width:${Math.round((v.count/maxCount)*100)}%"></div>
              </div>
              <span style="font-size:14px;font-weight:700;color:${v.color};font-family:monospace;width:20px;text-align:right">${v.count}</span>
            </div>
          `).join('')}
        </div>
      </div>
      ${cveItems.map(cve => `
        <div style="border:1px solid ${sevColors[cve.sev]||'#E2E8F0'};border-left:4px solid ${sevColors[cve.sev]||'#E2E8F0'};border-radius:6px;padding:12px 14px;margin-bottom:10px;background:#FAFAFA">
          <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px">
            <span style="font-family:monospace;font-size:11px;font-weight:700;color:${sevColors[cve.sev]}">${cve.id}</span>
            <span style="padding:2px 7px;background:${sevColors[cve.sev]}22;border:1px solid ${sevColors[cve.sev]};border-radius:3px;font-size:10px;font-weight:700;color:${sevColors[cve.sev]};font-family:monospace">CVSS ${cve.cvss}</span>
            <span style="padding:2px 7px;background:${sevColors[cve.sev]}22;border:1px solid ${sevColors[cve.sev]};border-radius:3px;font-size:10px;font-weight:700;color:${sevColors[cve.sev]}">${cve.sev}</span>
          </div>
          <div style="font-size:12px;font-weight:700;color:#0F172A;margin-bottom:6px">${cve.title}</div>
          <div style="font-size:11px;color:#00B89E">✓ ${lang==='ko'?'즉시 조치':'Action'}: ${cve.action}</div>
        </div>
      `).join('')}
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 8: 장치별 보안 등급표 ───
  const sortedDevices = [...devices].sort((a,b) => {
    const o = {Critical:0,High:1,Medium:2,Low:3}
    return (o[a.risk as keyof typeof o]??3)-(o[b.risk as keyof typeof o]??3)
  })

  const page8 = `
  <div style="${pageStyle}">
    ${headerHTML(8)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('06', lang==='ko'?'장치별 보안 등급표':'Device Security Grade', 'A~F Evaluation')}
      <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:18px">
        ${(['A','B','C','D','F'] as const).map(g => {
          const gColors = {A:'#2ECC71',B:'#00E5C8',C:'#F0A500',D:'#F03E3E',F:'#CC0000'}
          const cnt = sortedDevices.filter(d => {
            const s = d.risk==='Critical'?22:d.risk==='High'?52:d.risk==='Medium'?70:88
            const gd = s>=90?'A':s>=80?'B':s>=70?'C':s>=50?'D':'F'
            return gd===g
          }).length
          const gName = P.grades[g]
          return `
            <div style="background:${gColors[g]}22;border:1px solid ${gColors[g]};border-radius:8px;padding:10px;text-align:center">
              <div style="font-size:18px;font-weight:900;color:${gColors[g]}">${g}</div>
              <div style="font-size:10px;color:${gColors[g]};margin:2px 0">${gName}</div>
              <div style="font-size:20px;font-weight:700;color:${gColors[g]};font-family:monospace">${cnt}</div>
            </div>
          `
        }).join('')}
      </div>
      <table style="width:100%;border-collapse:collapse;font-size:11px">
        <thead>
          <tr style="background:#0F172A;color:white">
            ${['#', 'IP', lang==='ko'?'자산명':'Asset', lang==='ko'?'유형':'Type', lang==='ko'?'점수':'Score', lang==='ko'?'등급':'Grade', lang==='ko'?'위험도':'Risk'].map(h =>
              `<th style="padding:8px 10px;text-align:left;font-size:10px">${h}</th>`
            ).join('')}
          </tr>
        </thead>
        <tbody>
          ${sortedDevices.map((d,i) => {
            const score = d.risk==='Critical'?22:d.risk==='High'?52:d.risk==='Medium'?70:88
            const grade = score>=90?'A':score>=80?'B':score>=70?'C':score>=50?'D':'F'
            const gc = gradeColor(grade)
            const name = d.customName||d.host
            const isEdited = d.customName && d.customName!==d.host
            return `
              <tr style="background:${i%2===0?'#F8FAFC':'white'};border-bottom:1px solid #E2E8F0">
                <td style="padding:7px 10px;color:#94A3B8;font-family:monospace;font-size:10px">${i+1}</td>
                <td style="padding:7px 10px;font-family:monospace;font-size:10px;color:#0F172A">${d.ip}</td>
                <td style="padding:7px 10px;color:${isEdited?'#00B89E':'#0F172A'};font-weight:${isEdited?700:400};font-size:11px">${name}</td>
                <td style="padding:7px 10px;color:#475569;font-size:10px">${d.type}</td>
                <td style="padding:7px 10px;font-weight:700;color:${gc};font-family:monospace">${score}</td>
                <td style="padding:7px 10px;font-weight:900;color:${gc};font-family:monospace">${grade}</td>
                <td style="padding:7px 10px">${riskBadge(d.risk, lang)}</td>
              </tr>
            `
          }).join('')}
        </tbody>
      </table>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 9: 권고 조치 ───
  const actionGroups = [
    {
      title: P.immediateAction,
      color: '#F03E3E',
      bg: '#FFF5F5',
      items: lang==='ko' ? [
        'Telnet 비활성화 → SSH v2 전환 (Critical 장치 대상)',
        '기본 패스워드 즉시 변경 (영문+숫자+특수문자 12자 이상)',
        'EMR 서버 RDP 포트(3389) 방화벽 차단',
        'Windows 보안 패치 적용 (BlueKeep, Log4Shell)',
      ] : [
        'Disable Telnet → Switch to SSH v2 (Critical devices)',
        'Change default passwords immediately (12+ chars, mixed)',
        'Block EMR server RDP port (3389) via firewall',
        'Apply Windows security patches (BlueKeep, Log4Shell)',
      ]
    },
    {
      title: P.shortTermAction,
      color: '#F0A500',
      bg: '#FFFBEB',
      items: lang==='ko' ? [
        '별관 게이트웨이 펌웨어 업데이트',
        'OS 보안 업데이트 미적용 PC 일괄 패치 (8대)',
        '복합기 RAW Print 포트(9100) 접근 제한',
        '패스워드 정기 변경 정책 수립',
      ] : [
        'Update annex gateway firmware',
        'Batch OS security update for 8 PCs',
        'Restrict MFP RAW Print port (9100) access',
        'Establish regular password change policy',
      ]
    },
    {
      title: P.longTermAction,
      color: '#3B9EFF',
      bg: '#EFF6FF',
      items: lang==='ko' ? [
        'NAC 솔루션 도입 검토',
        'VLAN 세그멘테이션 구축',
        '게이트웨이 장비 교체 검토',
        '정기 보안 점검 체계 수립 (분기 1회)',
      ] : [
        'Evaluate NAC solution implementation',
        'Build VLAN segmentation',
        'Plan gateway equipment replacement',
        'Establish quarterly security inspection system',
      ]
    }
  ]

  const page9 = `
  <div style="${pageStyle}">
    ${headerHTML(9)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('07', lang==='ko'?'권고 조치 사항 및 이행 로드맵':'Recommendations & Roadmap', 'Action Roadmap')}
      ${actionGroups.map((ag, idx) => `
        <div style="border:1px solid ${ag.color};border-left:4px solid ${ag.color};border-radius:8px;padding:14px 16px;margin-bottom:12px;background:${ag.bg}">
          <div style="display:flex;align-items:center;gap:8px;margin-bottom:10px">
            <div style="width:22px;height:22px;background:${ag.color};border-radius:5px;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:11px;color:white">${idx+1}</div>
            <div style="font-size:13px;font-weight:700;color:${ag.color}">${ag.title}</div>
          </div>
          ${ag.items.map(item => `
            <div style="font-size:11.5px;color:#334155;padding:5px 0 5px 12px;border-left:2px solid ${ag.color};margin-bottom:5px">• ${item}</div>
          `).join('')}
        </div>
      `).join('')}

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-top:20px;margin-bottom:12px">■ ${P.roadmap}</div>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">
        ${[
          { period: lang==='ko'?'즉시 (1~2주)':'Immediate (1-2wk)', color:'#F03E3E', items: lang==='ko'?['Telnet→SSH 전환','패스워드 변경','RDP 방화벽 차단','EMR 패치']:['Telnet→SSH','Password Change','RDP Firewall','EMR Patch'] },
          { period: lang==='ko'?'단기 (1개월)':'Short-term (1mo)', color:'#F0A500', items: lang==='ko'?['OS 업데이트','GW 펌웨어','복합기 ACL','정책 수립']:['OS Update','GW Firmware','MFP ACL','Policy Setup'] },
          { period: lang==='ko'?'중장기 (분기)':'Long-term (Qtly)', color:'#3B9EFF', items: lang==='ko'?['NAC 도입','VLAN 구성','GW 교체','정기 점검']:['NAC Deploy','VLAN Setup','GW Replace','Regular Scan'] },
        ].map(r => `
          <div>
            <div style="background:${r.color};border-radius:6px 6px 0 0;padding:8px;text-align:center;font-size:11px;font-weight:700;color:white">${r.period}</div>
            ${r.items.map((item, j) => `
              <div style="background:${j%2===0?'#F8FAFC':'white'};border:1px solid #E2E8F0;border-top:none;padding:7px 10px;font-size:10.5px;color:#334155;text-align:center">${item}</div>
            `).join('')}
          </div>
        `).join('')}
      </div>
    </div>
    ${footerHTML()}
  </div>`

  // ─── PAGE 10: 부록 ───
  const glossaryItems = lang === 'ko' ? [
    ['CVE', 'Common Vulnerabilities and Exposures. 공개된 보안 취약점의 고유 식별 번호.'],
    ['CVSS', '취약점 심각도를 0~10점으로 수치화한 국제 표준 점수 체계.'],
    ['OUI', 'MAC 주소 앞 24비트로 제조사를 식별하는 IEEE 표준 (741개 등록됨).'],
    ['Telnet', '원격 접속 프로토콜. 모든 데이터를 평문 전송. SSH로 대체 필수.'],
    ['RDP', 'Windows 원격 접속 프로토콜 (포트: 3389). 외부 노출 시 위험.'],
    ['BlueKeep', 'CVE-2019-0708. Windows RDP Pre-auth RCE 취약점.'],
    ['Log4Shell', 'CVE-2021-44228. Apache Log4j2 JNDI 인젝션 취약점.'],
    ['VLAN', '물리 네트워크를 논리적으로 분리하는 기술.'],
    ['NAC', '비인가 장치 차단 및 보안 정책 준수 검사 솔루션.'],
  ] : [
    ['CVE', 'Common Vulnerabilities and Exposures. Unique identifier for publicly known security vulnerabilities.'],
    ['CVSS', 'Common Vulnerability Scoring System. International standard for rating vulnerability severity (0-10).'],
    ['OUI', 'Organizationally Unique Identifier. First 24 bits of MAC address for manufacturer identification.'],
    ['Telnet', 'Remote access protocol transmitting all data in plaintext. Must be replaced with SSH.'],
    ['RDP', 'Remote Desktop Protocol (port 3389). Dangerous when exposed externally.'],
    ['BlueKeep', 'CVE-2019-0708. Windows RDP Pre-authentication Remote Code Execution vulnerability.'],
    ['Log4Shell', 'CVE-2021-44228. Apache Log4j2 JNDI Injection Remote Code Execution vulnerability.'],
    ['VLAN', 'Virtual LAN technology for logical network segmentation.'],
    ['NAC', 'Network Access Control - blocks unauthorized devices and enforces security policies.'],
  ]

  const page10 = `
  <div style="${pageStyle}">
    ${headerHTML(10)}
    <div style="padding:28px 48px 60px">
      ${sectionHeader('08', lang==='ko'?'부록':'Appendix', 'Glossary & References')}

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:10px">■ ${P.glossary}</div>
      <table style="width:100%;border-collapse:collapse;font-size:11px;margin-bottom:24px">
        ${glossaryItems.map(([term, def], i) => `
          <tr style="background:${i%2===0?'#F8FAFC':'white'};border-bottom:1px solid #E2E8F0">
            <td style="padding:8px 12px;font-weight:700;color:#00B89E;font-family:monospace;white-space:nowrap;width:100px">${term}</td>
            <td style="padding:8px 12px;color:#334155;line-height:1.6">${def}</td>
          </tr>
        `).join('')}
      </table>

      <div style="font-size:12px;font-weight:700;color:#00E5C8;margin-bottom:10px">■ ${P.confirmation}</div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:20px">
        ${[
          [P.reportNumber, scan.reportNo||'NSP-2026-001'],
          [lang==='ko'?'버전':'Version', 'Premium Edition v2.0'],
          [lang==='ko'?'생성 도구':'Generated By', 'ScanAI v2.1'],
          [P.classification, P.classificationValue],
          [P.reportDate, scan.scanDate],
          [P.organization, org.company||'-'],
          [P.manager, org.manager||'-'],
          [lang==='ko'?'연락처':'Contact', `${org.phone||'-'} | ${org.email||'-'}`],
        ].map(([k,v]) => `
          <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:6px;padding:8px 12px">
            <div style="font-size:9px;color:#94A3B8;margin-bottom:3px;letter-spacing:.5px;text-transform:uppercase;font-family:monospace">${k}</div>
            <div style="font-size:11.5px;font-weight:600;color:#0F172A">${v}</div>
          </div>
        `).join('')}
      </div>

      <div style="background:#F0FDF9;border:1px solid #00B89E;border-radius:8px;padding:16px;text-align:center">
        <div style="font-size:11px;color:#334155;margin-bottom:4px">
          ${lang==='ko'
            ? '본 보고서는 ScanAI에 의해 자동 생성된 기밀 문서입니다. 무단 복제 및 외부 유출을 금지합니다.'
            : 'This report is a confidential document automatically generated by ScanAI. Unauthorized reproduction and external disclosure are prohibited.'}
        </div>
        <div style="font-size:12px;font-weight:700;color:#00E5C8">© ${new Date().getFullYear()} ScanAI · All Rights Reserved</div>
      </div>
    </div>
    ${footerHTML()}
  </div>`

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      ${googleFont}
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { background: white; }
      </style>
    </head>
    <body>
      ${page1}${page2}${page3}${page4}${page5}${page6}${page7}${page8}${page9}${page10}
    </body>
    </html>
  `
}

export async function generateScanAIReport(
  org: OrgInfo,
  devices: DeviceData[],
  scan: ScanInfo,
  lang: Lang = 'ko'
) {
  const { jsPDF } = await import('jspdf')
  const html2canvas = (await import('html2canvas')).default

  // 숨겨진 iframe에 HTML 렌더링
  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:794px;height:auto;border:none;visibility:hidden'
  document.body.appendChild(iframe)

  const html = buildReportHTML(org, devices, scan, lang)
  iframe.contentDocument!.open()
  iframe.contentDocument!.write(html)
  iframe.contentDocument!.close()

  // 폰트 로드 대기
  await new Promise(resolve => setTimeout(resolve, 2000))

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pages = iframe.contentDocument!.querySelectorAll('div[style*="794px"]')

  for (let i = 0; i < pages.length; i++) {
    const canvas = await html2canvas(pages[i] as HTMLElement, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      width: 794,
      windowWidth: 794,
    })

    const imgData = canvas.toDataURL('image/jpeg', 0.95)
    if (i > 0) doc.addPage()
    doc.addImage(imgData, 'JPEG', 0, 0, 210, 297)
  }

  document.body.removeChild(iframe)

  const companySlug = (org.company || 'Report').replace(/[^a-zA-Z0-9가-힣]/g, '_')
  const dateSlug = scan.scanDate.replace(/[^0-9]/g, '')
  const langSuffix = lang === 'en' ? '_EN' : '_KO'
  doc.save(`ScanAI_Report_${companySlug}_${dateSlug}${langSuffix}.pdf`)
}
